config/routes.rb
TaskList::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :tasks

  resources :users do
    collection do
      get :new
      get :search
    end
  end

  resources :sessions do
    collection do
      get :new
    end
  end

  root :to => "tasks#index"
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :id,
                  :created_at,
                  :updated_at,
                  :caption,
                  :description,
                  :user_id,
                  :user

  belongs_to :user

  validates_presence_of :caption
  validates_presence_of :description
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id,
                  :created_at,
                  :updated_at,
                  :name,
                  :surname,
                  :email,
                  :password,
                  :password_hash,
                  :password_salt,
                  :password_confirmation

  attr_accessor :password

  has_many :tasks

  before_save :encrypt_password

  validates :email, :presence => true,
            :length => {:minimum => 3, :maximum => 254},
            :uniqueness => true,
            :format => {:with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i}
  validates_confirmation_of :password
  validates_presence_of :password
  validates_presence_of :name
  validates_presence_of :surname

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def full_name
    name + ' ' + surname
  end

  def self.search_user query, limit = 5
    where(%Q{`name` LIKE '%#{query}%' OR `surname` LIKE '%#{query}%'}).limit(limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def authenticated?
    !session[:user_id].blank? && session[:expire_time] > Time.now
  end

  def check_authentication
    unless authenticated?
      flash[:error] = "You must be logged in to access this section"
      redirect_to :log_in
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      session[:expire_time] = 20.minutes.seconds.from_now

      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :log_in, :notice => "Logged out!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :check_authentication

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @task.user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_authentication, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def search
    if request.xhr?
      @users = User.search_user(params[:term]).map{|element| {:id => element.id, :value => %Q{#{element.name} #{element.surname}}}}

      render :json => @users
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TasksList
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    #user_nav
      - if current_user
        Logged in as #{current_user.email}.
        \#{link_to "Log out", log_out_path}
      - else
        = link_to "Sign up", sign_up_path
        or
        \#{link_to "log in", log_in_path}
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = yield

app/views/tasks/_form.html.haml
= simple_form_for @task do |form|

  -if @task.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this #{Task.name.titleize} from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :caption, :label => 'Caption'
  = form.input :description, :label => 'Description'

  %div{:class => "ui-widget input string required"}
    %label{:for => "user", :class => "text required control-label"}
      %abbr{:title => "required"}
        *
      User
    = hidden_field_tag("task[user_id]", @task.user.id)
    %input{:id => "user_name", :name =>"task_user_name", :class => "string required", :value => @task.user.full_name}

  .actions
    = form.button :submit

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%div{:id => :data_container}
  %table
    %tr
      %th Caption
      %th Full Name
      %th
      %th
      %th

    - @tasks.each do |task|
      %tr
        %td= task.caption
        %td= task.user.full_name
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path

%h1 Caption:
%p= @task.caption
%h2 Responsible person
%p= @task.user.full_name
%h3 Description
%p= @task.description

app/views/users/new.html.haml
%h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :surname
    %br/
    = f.text_field :surname
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %p.button= f.submit